### ISSUE TITLE
Select pagesize with ajax

### ISSUE THREAD

**Issue by serjlaw** [nkovacs/yii2-pagesizer#1]
Hello.
Your widget is very useful. Thank you for him.
I have listview and search which is sent by ajax(post). When I select the page size, the search disappears.

**Comment by nkovacs** [comment]
Hi
What do you mean by search? A separate form above the listview?

When you select a page size, does it reload the listview via ajax? Does selecting another page or changing the order also reload the listview via ajax? Does that make the search disappear?

The way it works is that the server renders the listview again, sends it back via ajax, and then the existing listview is replaced by the new one. This happens when you change the page or the sort too, so the bug shouldn't be specific to this widget.

**Comment by serjlaw** [comment]
Thanks for the quick response. Yes, the problem is not in your widget. The problem is global and it can not be solved. I went around it using the session.
